version: "3.8"
services:
  app:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    ports:
      - 3000:3000

  prod:
    build:
      context: .
      target: prod
    ports:
      - 3000:3000
